// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Warframe_Utils_.NET.Data;

#nullable disable

namespace Warframe_Utils_.NET.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260113120000_AddPriceAlertSystem")]
    partial class AddPriceAlertSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // PriceAlert Entity Configuration
            modelBuilder.Entity("Warframe_Utils_.NET.Models.PriceAlert", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<decimal>("AlertPrice")
                    .HasColumnType("numeric");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<decimal?>("CurrentPrice")
                    .HasColumnType("numeric");

                b.Property<bool>("IsAcknowledged")
                    .HasColumnType("boolean");

                b.Property<bool>("IsActive")
                    .HasColumnType("boolean");

                b.Property<string>("ItemId")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<string>("ItemName")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<DateTime?>("LastCheckedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<bool>("IsTriggered")
                    .HasColumnType("boolean");

                b.Property<DateTime?>("TriggeredAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("IsActive", "IsTriggered")
                    .HasDatabaseName("IX_PriceAlerts_IsActive_IsTriggered");

                b.HasIndex("UserId")
                    .HasDatabaseName("IX_PriceAlerts_UserId");

                b.ToTable("PriceAlerts");
            });

            // AlertNotification Entity Configuration
            modelBuilder.Entity("Warframe_Utils_.NET.Models.AlertNotification", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<bool>("IsRead")
                    .HasColumnType("boolean");

                b.Property<string>("Message")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("PriceAlertId")
                    .HasColumnType("integer");

                b.Property<DateTime?>("ReadAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<decimal>("TriggeredPrice")
                    .HasColumnType("numeric");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("PriceAlertId")
                    .HasDatabaseName("IX_AlertNotifications_PriceAlertId");

                b.HasIndex("UserId")
                    .HasDatabaseName("IX_AlertNotifications_UserId");

                b.HasIndex("UserId", "IsRead")
                    .HasDatabaseName("IX_AlertNotifications_UserId_IsRead");

                b.HasOne("Warframe_Utils_.NET.Models.PriceAlert", "PriceAlert")
                    .WithMany()
                    .HasForeignKey("PriceAlertId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("PriceAlert");

                b.ToTable("AlertNotifications");
            });
#pragma warning restore 612, 618
        }
    }
}
